[Interface]
Address = 10.66.66.1/24,fd42:42:42::1/64
ListenPort = 51820
PrivateKey = WICjaMEDwyQb66KOqtHjFclJf0HC3QH20wBQsnV4R14=

### Client alice
[Peer]
PublicKey = WRnSf8viYeZdpxY5zuYqTuR/Q530227o2v84qt/gcGY=
PresharedKey = K1Kz13Ypi8kQWgfrjHmUkvgoltMzg+DBy53skmxhhZ8=
AllowedIPs = 10.66.66.2/32,fd42:42:42::2/128
